model_name: "oww_fensterbruch_v02"
output_dir: "Data_Frame/data/oww_fensterbruch_v02"

# Da wir keine Sprache generieren, sind diese Felder egal, müssen aber da sein:
target_phrase: ["fensterbruch"] 
custom_negative_phrases: []
n_samples: 1000
n_samples_val: 100
tts_batch_size: 50
piper_sample_generator_path: "./"

# Augmentation (Hier passiert die Magie)
augmentation_batch_size: 16
augmentation_rounds: 50 # Erstellt 50 leicht veränderte Versionen aus jedem deiner 112 Clips!

# Pfade zu den generellen Hintergrundgeräuschen (die du in Schritt 2 geladen hast)
false_positive_validation_data_path: "OpenWakeWord_v02/validation_set_features.npy"
feature_data_files:
  "ACAV100M_sample": "OpenWakeWord_v02/openwakeword_features_ACAV100M_2000_hrs_16bit.npy"

# Batch-Konfiguration (Wie viele Clips pro Trainingsschritt)
batch_n_per_class:
  "ACAV100M_sample": 1024
  "adversarial_negative": 50 # Das sind deine Flaschen/Umgebungsgeräusche
  "positive": 50             # Das sind deine Fensterbrüche

# Modell-Größe und Trainingsschritte
model_type: "dnn" # dnn --> Deep Neural Network
layer_size: 32 # --> 32 Neuronen pro Schicht
steps: 15000

max_negative_weight: 1500
target_false_positives_per_hour: 0.2